language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
otp_release:
  - 20.3
  - 21.3
  - 22.0

matrix:
  exclude:
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.10
      opt_release: 20.3
