language: elixir
elixir:
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
otp_release:
  - 20.3
  - 21.3
  - 22.3
  - 23.3
  - 24.0

matrix:
  exclude:
    - elixir: 1.8
      opt_release: 23.3
    - elixir: 1.8
      opt_release: 24.0
    - elixir: 1.9
      opt_release: 23.3
    - elixir: 1.9
      opt_release: 24.0
    - elixir: 1.10
      opt_release: 20.3
    - elixir: 1.11
      opt_release: 20.3
    - elixir: 1.12
      opt_release: 20.3
    - elixir: 1.12
      opt_release: 21.3
