name: Build Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        elixir: [1.15, 1.16, 1.17]
        otp: [24, 25, 26, 27]
        exclude:
          - elixir: 1.15
            otp: 27
          - elixir: 1.16
            otp: 27
          - elixir: 1.17
            otp: 24


    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
